version: '3.8'

services:
  application:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: takotekno_page
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.takopages.rule=Host(`takotekno.solutions`)"  # Arahkan ke takotekno.solutions
      - "traefik.http.routers.takopages.entrypoints=http"
      - "traefik.http.middlewares.takopages-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.takopages.middlewares=takopages-https-redirect"
      - "traefik.http.routers.takopages-secure.rule=Host(`takotekno.solutions`)"  # Arahkan ke takotekno.solutions
      - "traefik.http.routers.takopages-secure.entrypoints=https"
      - "traefik.http.routers.takopages-secure.tls=true"
      - "traefik.http.routers.takopages-secure.tls.certresolver=http"
      - "traefik.http.routers.takopages-secure.service=takopages"
      - "traefik.http.services.takopages.loadbalancer.server.port=3000"  # Port yang digunakan oleh Nginx
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
