version: '3.8'

services:
  application:
    image: ${DOCKER_USERNAME}/takotekno-page:latest
    container_name: takotekno_page
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 100M

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.takopages.rule=Host(`takotekno.biz.id`)"
      - "traefik.http.routers.takopages.entrypoints=web"
      - "traefik.http.middlewares.takopages-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.takopages.middlewares=takopages-https-redirect"
      - "traefik.http.routers.takopages-secure.rule=Host(`takotekno.biz.id`)"
      - "traefik.http.routers.takopages-secure.entrypoints=websecure"
      - "traefik.http.routers.takopages-secure.tls=true"
      - "traefik.http.routers.takopages-secure.tls.certresolver=http"
      - "traefik.http.routers.takopages-secure.service=takopages"
      - "traefik.http.services.takopages.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

    networks:
      - proxy

networks:
  proxy:
    external: true
